name: gitclone
version: 0.0.1
inputs:
- name: FLOWCI_GIT_URL
  type: string
  required: true
- name: FLOWCI_GIT_BRANCH
  type: string
  required: true
- name: FLOWCI_GIT_REPO
  type: string
  required: true
- name: FLOWCI_CREDENTIAL_SSH_RSA
  type: string
  required: false

script: |
  echo '#################### GIT CLONE ####################'
  
  export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  
  if [[ ! -n $FLOWCI_CREDENTIAL_SSH_RSA ]]; then
  
    echo '**** start clone ****'
    rm -rf ${FLOWCI_GIT_REPO} 2> /dev/null
    git clone -b ${FLOWCI_GIT_BRANCH} ${FLOWCI_GIT_URL} ${FLOWCI_GIT_REPO}
  
  else
  
    echo '**** config ssh ****'
    export PK_FILE=id_rsa_${FLOWCI_CREDENTIAL_SSH_RSA}
    echo '--------- pk file ---------'
    echo ${PK_FILE}
    echo '--------- pk file ---------'
    
    rm -f ${PK_FILE} 2> /dev/null
    curl -o ${PK_FILE} ${FLOWCI_SERVER_URL}/api/credential/${FLOWCI_CREDENTIAL_SSH_RSA}
    chmod 600 ${PK_FILE}
      
    echo '**** start clone ****'
    rm -rf ${FLOWCI_GIT_REPO} 2> /dev/null
    ssh-agent bash -c 'ssh-add ${PK_FILE}; git clone -b ${FLOWCI_GIT_BRANCH} ${FLOWCI_GIT_URL} ${FLOWCI_GIT_REPO}'
   
  fi
  
  echo '#################### FINISH ####################'
