name: gitclone
version: 1.0.0
icon: "git.svg"

inputs:
  - name: FLOWCI_GIT_URL
    type: string
    required: true
  - name: FLOWCI_GIT_BRANCH
    type: string
    value: master
    required: false
  - name: FLOWCI_GIT_COMMIT_ID
    type: string
    required: false
  - name: FLOWCI_GIT_REPO
    type: string
    required: true
  - name: FLOWCI_GIT_CREDENTIAL
    type: string
    required: false
  - name: FLOWCI_GITCLONE_TIMEOUT
    type: int
    required: false
    value: 60
    
exports:
  - "FLOWCI_GIT_AUTHOR"
  - "FLOWCI_GIT_COMMIT_ID"
  - "FLOWCI_GIT_COMMIT_MESSAGE"
  - "FLOWCI_GIT_COMMIT_TIME"
  
script: |
  python3 -m pip install gitpython

  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/gitclone
  python3 ${plugindir}/src/gitclone.py
