name: gitclone
version: 1.0.0
icon: "git.svg"

tags:
- "git"

inputs:
- name: FLOWCI_GIT_URL
  type: string
  required: true
- name: FLOWCI_GIT_BRANCH
  type: string
  required: true
- name: FLOWCI_GIT_REPO
  type: string
  required: true
- name: FLOWCI_CREDENTIAL_NAME
  type: string
  required: false

script: |
  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/gitclone
  pip3 install gitpython
  python3 ${plugindir}/src/gitclone.py
