name: gitclone
version: 1.2.0
icon: "git.svg"

inputs:
  - name: FLOWCI_GIT_URL
    type: string
    required: true
  - name: FLOWCI_GIT_BRANCH
    type: string
    value: master
    required: false
  - name: FLOWCI_GIT_COMMIT_ID
    type: string
    required: false
  - name: FLOWCI_GIT_CREDENTIAL
    type: string
    required: false
  - name: FLOWCI_GITCLONE_TIMEOUT
    type: int
    required: false
    value: 60
  - name: FLOWCI_PIP_SOURCE
    type: string
    required: false
  
bash: |
  if [ -z $FLOWCI_PIP_SOURCE ]; then
    python3 -m pip install gitpython
  else
    echo "install gitpython from source $FLOWCI_PIP_SOURCE"
    python3 -m pip install gitpython -i $FLOWCI_PIP_SOURCE
  fi

  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/gitclone
  python3 ${plugindir}/src/gitclone.py
