name: gitclone
version: 0.0.1
inputs:
- name: GIT_URL
  type: string
  required: true
- name: GIT_BRANCH
  type: string
  required: true
- name: GIT_RSA_CREDENTIAL
  type: string
  required: true

script: |
  export PK_FILE=id_rsa
  rm ${PK_FILE} 2> /dev/null

  wget -O ${PK_FILE} ${FLOWCI_SERVER_URL}/open/credential/rsa/${GIT_RSA_CREDENTIAL}/private
  chmod 600 ${PK_FILE}

  ssh-agent bash -c 'ssh-add ${PK_FILE}; git clone -b ${GIT_BRANCH} ${GIT_URL}'